name: jeremiak
url: www.jeremiak.com
description: my things
markdown: redcarpet
highlighter: pygments
timezone: America/New_York

collections:
  projects:
    output: true
    permalink: /projects/:path/
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
destination: public
exclude:
  - vendor
source: source
