name: jeremiak
url: www.jeremiak.com
description: just a small personal site
markdown: redcarpet
highlighter: pygments
timezone: America/New_York

collections:
  projects:
    permalink: /projects/:path/
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
permalink: /posts/:title/
destination: public
exclude:
  - vendor
source: source
