name: jeremiak
markdown: redcarpet
pygments: true
timezone: America/Los_Angeles
prose:
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "text"
      - name: "title"
        field:
          element: "text"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: true
